# Generated by Django 3.0.4 on 2021-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleusuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleusuario',
            name='correoUsuario',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
