# Generated by Django 3.0.4 on 2020-07-07 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caso', '0003_caso_persona'),
        ('detallecaso', '0002_detallecaso_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecaso',
            name='Caso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caso.Caso'),
        ),
    ]
