# Generated by Django 3.0.4 on 2020-06-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='Usuario',
        ),
    ]
