# Generated by Django 3.1.7 on 2021-10-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocaso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de elimnacion')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'modelo base',
                'verbose_name_plural': 'BaseModels',
                'abstract': False,
            },
        ),
    ]
