# Generated by Django 3.1.7 on 2021-10-29 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detallecaso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de elimnacion')),
                ('descripccion', models.CharField(max_length=200)),
                ('porcentaje', models.CharField(max_length=200)),
                ('Caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caso.caso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'modelo base',
                'verbose_name_plural': 'BaseModels',
                'abstract': False,
            },
        ),
    ]
