# Generated by Django 3.0.4 on 2020-07-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200621_2110'),
        ('detallecaso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecaso',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
