# Generated by Django 3.1.7 on 2022-01-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detallecaso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecaso',
            name='usuario',
        ),
    ]
