# Generated by Django 3.0.4 on 2021-04-22 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caso', '0003_caso_persona'),
        ('detallecaso', '0003_auto_20200706_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecaso',
            name='Caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caso.Caso'),
        ),
    ]
