# Generated by Django 3.0.4 on 2020-05-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('rol', '0002_rol_nombrerol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.Rol')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
