# Generated by Django 3.0.4 on 2020-06-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200621_2110'),
        ('detalleusuario', '0002_auto_20200620_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleusuario',
            name='persona',
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
