# Generated by Django 3.1.7 on 2021-10-29 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '__first__'),
        ('tipocaso', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de elimnacion')),
                ('Estado', models.CharField(max_length=200)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('Tipocaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipocaso.tipocaso')),
            ],
            options={
                'verbose_name': 'modelo base',
                'verbose_name_plural': 'BaseModels',
                'abstract': False,
            },
        ),
    ]
