# Generated by Django 3.1.7 on 2021-09-02 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('tipocaso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=200)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('Tipocaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipocaso.tipocaso')),
            ],
        ),
    ]
