# Generated by Django 3.0.4 on 2020-07-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_persona_user'),
        ('caso', '0002_remove_caso_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='Persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
            preserve_default=False,
        ),
    ]
