# Generated by Django 3.1.7 on 2021-09-02 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de elimnacion')),
                ('correoUsuario', models.CharField(max_length=200)),
                ('contrasenaUsuario', models.CharField(max_length=200)),
                ('Persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to='persona.persona')),
            ],
            options={
                'verbose_name': 'modelo base',
                'verbose_name_plural': 'BaseModels',
                'abstract': False,
            },
        ),
    ]
