# Generated by Django 3.0.4 on 2020-06-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_persona_user'),
        ('usuario', '0002_auto_20200621_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correoUsuario', models.CharField(max_length=200)),
                ('contrasenaUsuario', models.CharField(max_length=200)),
                ('Persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
