# Generated by Django 3.0.4 on 2021-04-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_persona_user'),
        ('usuario', '0004_auto_20210419_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasenaUsuario',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='correoUsuario',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
