# Generated by Django 3.0.4 on 2021-04-19 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0003_auto_20200621_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Persona',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenaUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correoUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
